-- AlterTable
ALTER TABLE "Emotion" ADD COLUMN     "aiLabel" TEXT,
ADD COLUMN     "aiModel" TEXT,
ADD COLUMN     "aiVersion" TEXT,
ADD COLUMN     "negative" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "neutral" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "positive" DOUBLE PRECISION DEFAULT 0,
ALTER COLUMN "emoji" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Reflection" ADD COLUMN     "date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
